/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 */
#ifndef TESTER_HARMONY_KEYBOARD_CONTROLLER_SRC_MAIN_CPP_RNKEYBOARDCONTROLLER_H
#define TESTER_HARMONY_KEYBOARD_CONTROLLER_SRC_MAIN_CPP_RNKEYBOARDCONTROLLER_H

#ifndef RNKEYBOARDCONTROLLER_H
#define RNKEYBOARDCONTROLLER_H

/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 */

/**
 * This code was generated by "react-native codegen-harmony"
 *
 * Do not edit this file as changes may cause incorrect behavior and will be
 * lost once the code is regenerated.
 *
 * @generatorVersion: 1
 */
#pragma once

#include "RNOH/ArkTSTurboModule.h"

namespace rnoh {

class JSI_EXPORT KeyboardController : public ArkTSTurboModule {
  public:
    KeyboardController(const ArkTSTurboModule::Context ctx, const std::string name);
};

} // namespace rnoh

#endif

#endif
