/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 */

/**
 * This code was generated by "react-native codegen-harmony"
 *
 * Do not edit this file as changes may cause incorrect behavior and will be
 * lost once the code is regenerated.
 *
 * @generatorVersion: 1
 */
#include "RNStatusBarManagerCompat.h"

namespace rnoh {
using namespace facebook;

StatusBarManagerCompat::StatusBarManagerCompat(const ArkTSTurboModule::Context ctx, const std::string name) : ArkTSTurboModule(ctx, name)
{
    methodMap_ = {
        ARK_METHOD_METADATA(getConstants, 0),
        ARK_METHOD_METADATA(setHidden, 1),
        ARK_METHOD_METADATA(setColor, 2),
        ARK_METHOD_METADATA(setTranslucent, 1),
        ARK_METHOD_METADATA(setStyle, 1),
    };
}

} // namespace rnoh
